# Release Pilot configuration for itself (dogfooding!)
#
# This action uses itself to manage its own releases.
# GitHub Actions are "published" by pushing tags - the dist/ directory
# is staged before release and included in the version commit.

packages:
  - name: release-pilot
    ecosystem: custom
    # Update VERSION file - this also triggers a commit which includes
    # the staged dist/ directory (needed for the action to work)
    updateVersionFile: true
    publish: false

git:
  floatingTags: true

# Generate CHANGELOG.md from merged PRs
changelog:
  enabled: true
  file: CHANGELOG.md

# Keep version references up to date in README and examples
versionFiles:
  enabled: true
  files:
    # README.md action references
    - file: README.md
      pattern: 'uses: a-line-services/release-pilot@v[0-9]+'
      replace: 'uses: a-line-services/release-pilot@v{major}'

    # Example workflow files
    - file: examples/simple-npm/.github/workflows/release.yml
      pattern: 'uses: a-line-services/release-pilot@v[0-9]+'
      replace: 'uses: a-line-services/release-pilot@v{major}'

    - file: examples/monorepo/.github/workflows/release.yml
      pattern: 'uses: a-line-services/release-pilot@v[0-9]+'
      replace: 'uses: a-line-services/release-pilot@v{major}'

    - file: examples/rust-crate/.github/workflows/release.yml
      pattern: 'uses: a-line-services/release-pilot@v[0-9]+'
      replace: 'uses: a-line-services/release-pilot@v{major}'

    - file: examples/python-package/.github/workflows/release.yml
      pattern: 'uses: a-line-services/release-pilot@v[0-9]+'
      replace: 'uses: a-line-services/release-pilot@v{major}'

    - file: examples/go-module/.github/workflows/release.yml
      pattern: 'uses: a-line-services/release-pilot@v[0-9]+'
      replace: 'uses: a-line-services/release-pilot@v{major}'

    - file: examples/docker-image/.github/workflows/release.yml
      pattern: 'uses: a-line-services/release-pilot@v[0-9]+'
      replace: 'uses: a-line-services/release-pilot@v{major}'

    - file: examples/multi-ecosystem/.github/workflows/release.yml
      pattern: 'uses: a-line-services/release-pilot@v[0-9]+'
      replace: 'uses: a-line-services/release-pilot@v{major}'
