# Release Pilot configuration for itself (dogfooding!)
#
# This action uses itself to manage its own releases.
# GitHub Actions are "published" by pushing tags - the dist/ directory
# is committed and action.yml references it.

packages:
  - name: release-pilot
    ecosystem: custom
    updateVersionFile: false
    publish: false

version:
  devRelease: true

git:
  floatingTags: true
